# Generated by Django 4.0.2 on 2022-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_book', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbook',
            name='present_account',
        ),
        migrations.AddField(
            model_name='accountbook',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accountbook',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='accountbook',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='accountbook',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accountbook',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='accountbook',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
